#lang racket
(provide (all-defined-out))
(define (show str n char)
  (printf str (make-string n char))
  (newline))
(define (make-histogram l m h)
  (show "L: ~a" l #\|)
  (show "M: ~a" m #\|)
  (show "H: ~a" h #\|)
  (show "~a" 10 #\-))
